# Generated by Django 2.2.17 on 2020-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataguru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nohp', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=225, null=True)),
                ('biaya', models.IntegerField(null=True)),
                ('no_id', models.IntegerField(blank=True, null=True)),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='datamurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nohp', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=225, null=True)),
                ('pnd', models.CharField(blank=True, max_length=200)),
                ('usia', models.IntegerField(null=True)),
                ('no_id', models.IntegerField(blank=True, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
