# Generated by Django 2.2.17 on 2020-12-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamurid',
            name='pnd',
        ),
    ]
