# Generated by Django 2.2.17 on 2020-12-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_datamurid_pnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamurid',
            name='pnd',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='datamurid',
            name='nama',
            field=models.CharField(max_length=300),
        ),
    ]
