# Generated by Django 2.2 on 2020-11-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iwak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_iwak', models.TextField(default='')),
                ('nama_iwak', models.TextField(default='default')),
                ('harga', models.TextField(default='default')),
                ('stok', models.TextField(default='default')),
            ],
        ),
    ]
