# Generated by Django 2.2 on 2020-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iwak',
            name='jenis',
            field=models.TextField(default='default'),
        ),
    ]
