# Generated by Django 2.2 on 2020-11-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwak', '0002_iwak_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iwak',
            name='stok',
        ),
    ]
