# Generated by Django 2.2 on 2020-10-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ikan', models.TextField(default='')),
                ('nama', models.TextField(default='default')),
                ('harga', models.TextField(default='default')),
                ('diskon', models.TextField(default='default')),
            ],
        ),
    ]
