# Generated by Django 2.2 on 2020-10-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ikan',
            old_name='nama',
            new_name='jenis',
        ),
    ]
