# Generated by Django 2.2 on 2020-11-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikan', '0002_auto_20201030_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikan',
            name='nama',
            field=models.TextField(default=''),
        ),
    ]
