# Generated by Django 2.2 on 2020-11-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikan', '0003_ikan_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ikan',
            old_name='harga',
            new_name='harga_kiloan',
        ),
        migrations.AddField(
            model_name='ikan',
            name='harga_satuan',
            field=models.TextField(default='default'),
        ),
    ]
