# Generated by Django 2.2.17 on 2020-12-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='norole',
            field=models.CharField(choices=[('2', 'Vendor'), ('3', 'Client')], max_length=200, null=True),
        ),
    ]
