# Generated by Django 2.2 on 2020-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='penjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pnjual', models.TextField(default='')),
                ('nama_pnjual', models.TextField(default='default')),
                ('email', models.TextField(default='default')),
                ('no_telf', models.TextField(default='default')),
                ('data_ikan', models.TextField(default='default')),
                ('terjual_ikan', models.TextField(default='default')),
                ('stok', models.TextField(default='default')),
            ],
        ),
    ]
