# Generated by Django 2.2 on 2020-11-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjual',
            old_name='stok_ikan',
            new_name='no_telf',
        ),
        migrations.AddField(
            model_name='penjual',
            name='stok_ikan_hias',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='penjual',
            name='stok_ikan_konsum',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='penjual',
            name='total_terjual',
            field=models.TextField(default='default'),
        ),
    ]
