# Generated by Django 2.2 on 2020-11-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjual',
            old_name='terjual_ikan',
            new_name='ikan_terjual',
        ),
    ]
