# Generated by Django 2.2 on 2020-11-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjual', '0002_auto_20201102_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjual',
            old_name='nama_pnjual',
            new_name='nm_penjual',
        ),
    ]
