# Generated by Django 2.2 on 2020-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pmbli', models.TextField(default='')),
                ('nama_pmbli', models.TextField(default='default')),
                ('alamat', models.TextField(default='default')),
                ('total_beli', models.TextField(default='default')),
            ],
        ),
    ]
