# Generated by Django 2.2 on 2020-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembeli',
            name='total_beli',
            field=models.IntegerField(default='default'),
        ),
    ]
