# Generated by Django 2.2 on 2020-10-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201028_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Jenis_Makanan',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Warna',
            field=models.TextField(default='iqlima'),
        ),
    ]
