# Generated by Django 2.2 on 2020-10-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201028_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Nama',
            field=models.TextField(null=True),
        ),
    ]
