# Generated by Django 2.2 on 2020-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20201028_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Warna',
            field=models.TextField(default='hijau'),
        ),
    ]
