# Generated by Django 2.2 on 2020-10-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20201029_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Warna',
            field=models.TextField(default=''),
        ),
    ]
