# Generated by Django 2.2 on 2020-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20201029_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Warna',
            field=models.TextField(default='pilih warna'),
        ),
    ]
